

# RV32译码表

ISA = "RV32"
XLEN = 32

[CONST]
OP-32   = 0b011_0011
LOAD    = 0b000_0011
STORE   = 0b010_0011
OP-IMM  = 0b001_0011
SYSTEM  = 0b111_0011
MISC-MEM= 0b000_1111
BRANCH  = 0b110_0011
JAL     = 0b110_1111
JALR    = 0b110_0111
LUI     = 0b011_0111
AUIPC   = 0b001_0111
MULDIV  = 0b000_0001 # func7

[field]     # R指令的feild不会随指令变化
opcode  = [0,1,2,3,4,5,6]
rd      = [7,8,9,10,11]
func3   = [12,13,14]
rs1     = [15,16,17,18,19]
rs2     = [20,21,22,23,24]
func7   = [25,26,27,28,29,30,31]

[extensions]
#----------------------- I extention ---------------------------
[extensions.I.alu_2op]
set_flag = ["r_type","is_alu"]
out_field = ["rd","rs1","rs2"]
op.add = {opcode = "OP-32", func7 = 0b000_0000, func3 = 0b000}
op.sub = {opcode = "OP-32", func7 = 0b010_0000, func3 = 0b000}
op.sll = {opcode = "OP-32", func7 = 0b000_0000, func3 = 0b001}
op.slt = {opcode = "OP-32", func7 = 0b000_0000, func3 = 0b010}
op.sltu= {opcode = "OP-32", func7 = 0b000_0000, func3 = 0b011}
op.xor = {opcode = "OP-32", func7 = 0b000_0000, func3 = 0b100}
op.srl = {opcode = "OP-32", func7 = 0b000_0000, func3 = 0b101}
op.sra = {opcode = "OP-32", func7 = 0b010_0000, func3 = 0b101}
op.or  = {opcode = "OP-32", func7 = 0b000_0000, func3 = 0b110}
op.and = {opcode = "OP-32", func7 = 0b000_0000, func3 = 0b111}

[extensions.I.alu_1op]
set_flag  = ["i_type","is_alu"]
field     = {imm = [20,21,22,23,24,25,26,27,28,29,30,31]}
imm_offset= 0
out_field = ["rd","rs1","imm"]
op.addi   = {opcode = "OP-IMM",func3 = 0b000}
op.slti   = {opcode = "OP-IMM",func3 = 0b001}
op.sltiu  = {opcode = "OP-IMM",func3 = 0b010}
op.xori   = {opcode = "OP-IMM",func3 = 0b100}
op.ori    = {opcode = "OP-IMM",func3 = 0b110}
op.andi   = {opcode = "OP-IMM",func3 = 0b111}

[extensions.I.shift_imm]
set_flag  = ["i_type","is_alu"]
field     = {imm = [25,26,27,28,29,30,31],shamt = [20,21,22,23,24]}
imm_offset= 0
out_field = ["rd","rs1","shamt"]
op.slli   = {opcode = "OP-IMM",func3 = 0b001,imm = 0b000_0000}
op.srli   = {opcode = "OP-IMM",func3 = 0b101,imm = 0b000_0000}
op.srai   = {opcode = "OP-IMM",func3 = 0b101,imm = 0b010_0000}


[extensions.I.cond_br]
set_flag  = ["is_branch","b_type"]
field     = {imm = [8,9,10,11,25,26,27,28,29,30,7,31]}
imm_offset= 1
out_field = ["rs1","rs2","imm"]
op.beq    = {opcode = "BRANCH", func3 = 0b000}
op.bne    = {opcode = "BRANCH", func3 = 0b001}
op.blt    = {opcode = "BRANCH", func3 = 0b100}
op.bge    = {opcode = "BRANCH", func3 = 0b100}
op.bltu   = {opcode = "BRANCH", func3 = 0b110}
op.bgeu   = {opcode = "BRANCH", func3 = 0b111}

[extensions.I.jal]
set_flag  = ["j_type","uncond_br",'is_branch']
field     = {imm = [21,22,23,24,25,26,27,28,29,30,20,12,13,14,15,16,17,18,19,31]}
imm_offset= 1
out_field = ["rd","imm"]
op.jal    = {opcode = "JAL"}

[extensions.I.jalr]
set_flag  = ["i_type","uncond_br",'is_branch']
field     = {imm = [20,21,22,23,24,25,26,27,28,29,30,31]}
imm_offset= 0
out_field = ["rd","rs1","imm"]
op.jalr   = {opcode = "JALR",func3 = 0b000}

[extensions.I.load]
set_flag  = ["i_type","is_lsu",]
field     = {imm = [20,21,22,23,24,25,26,27,28,29,30,31]}
imm_offset= 0
out_field = ["rd","rs1","imm"]
op.lb     = {opcode = "LOAD",func3 = 0b000}
op.lh     = {opcode = "LOAD",func3 = 0b001}
op.lw     = {opcode = "LOAD",func3 = 0b010}
op.lbu    = {opcode = "LOAD",func3 = 0b100}
op.lhu    = {opcode = "LOAD",func3 = 0b101}

[extensions.I.store]
set_flag  = ["s_type","is_lsu",]
field     = {imm = [7,8,9,10,11,25,26,27,28,29,30,31]}
imm_offset= 0
out_field = ["rs2","rs1","imm"]
op.sb     = {opcode = "STORE",func3 = 0b000}
op.sh     = {opcode = "STORE",func3 = 0b001}
op.sw     = {opcode = "STORE",func3 = 0b010}

[extensions.I.load_imme]
set_flag  = ["u_type"]
field     = {imm = [12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31]}
imm_offset= 12
out_field = ["rd","imm"]
op.lui    = {opcode = "LUI"}
op.auipc  = {opcode = "AUIPC"}

[extensions.I.uop]
set_flag  = ["i_type"]
field     = {imm = [20,21,22,23,24,25,26,27,28,29,30,31]}
op.uop    = {opcode = "OP-IMM",func3 = 0b000,imm = 0b0000_0000_0000,rs1 = 0b0_0000,rd = 0b0_0000}

[extensions.I.sys]
set_flag  = ["i_type"]
field     = {imm = [20,21,22,23,24,25,26,27,28,29,30,31]}
op.ecall  = {opcode = "SYSTEM",func3 = 0b000,rs1 = 0b0_0000,rd = 0b0_0000,imm = 0b0000_0000_0000}
op.ebreak = {opcode = "SYSTEM",func3 = 0b000,rs1 = 0b0_0000,rd = 0b0_0000,imm = 0b0000_0000_0001}

[extensions.I.mem]
set_flag  = ["i_type"]
field     = {succ = [20,21,22,23], pred = [24,25,26,27], fm = [28,29,30,31]}
out_field = ["rd","rs1","succ","pred","fm"]
op.fence  = {opcode = "MISC-MEM",func3 = 0b000}
op.fence_tso = {opcode = "MISC-MEM",func3 = 0b000,rs1 = 0b0_0000,rd = 0b0_0000,succ=0b0011,pred=0b0011,fm=0b1000}
op.pause     = {opcode = "MISC-MEM",func3 = 0b000,rs1 = 0b0_0000,rd = 0b0_0000,succ=0b0000,pred=0b0001,fm=0b0000}



#----------------------- M extention ---------------------------
[extensions.M.mul]
out_field = ["rd","rs1","rs2"]
set_flag = ["r_type"]
op.mul    = {opcode = "OP-32", func7 = "MULDIV", func3 = 0b000}
op.mulh   = {opcode = "OP-32", func7 = "MULDIV", func3 = 0b001}
op.mulhsu = {opcode = "OP-32", func7 = "MULDIV", func3 = 0b010}
op.mulhu  = {opcode = "OP-32", func7 = "MULDIV", func3 = 0b011}

[extensions.M.div]
out_field = ["rd","rs1","rs2"]
set_flag = ["r_type"]
op.div    = {opcode = "OP-32", func7 = "MULDIV", func3 = 0b100}
op.divu   = {opcode = "OP-32", func7 = "MULDIV", func3 = 0b101}
op.rem    = {opcode = "OP-32", func7 = "MULDIV", func3 = 0b110}
op.remu   = {opcode = "OP-32", func7 = "MULDIV", func3 = 0b111}


#----------------------- zicsr extention ---------------------------

[extensions.zicsr.csr]
set_flag  = ["i_type"]
field     = {csr = [20,21,22,23,24,25,26,27,28,29,30,31]}
out_field = ["csr","rs1","rd"]
op.csrrw  = {opcode = "SYSTEM",func3 = 0b001}
op.csrrs  = {opcode = "SYSTEM",func3 = 0b010}
op.csrrc  = {opcode = "SYSTEM",func3 = 0b011}
op.csrrwi = {opcode = "SYSTEM",func3 = 0b101}
op.csrrsi = {opcode = "SYSTEM",func3 = 0b101}
op.csrrci = {opcode = "SYSTEM",func3 = 0b101}

